#!/bin/sh
# Guest PID1 helper (after osg-init): optional noVNC stack, then sleep.
set -eu
if [ "${DISPLAY_MODE:-none}" = "novnc" ]; then
  /usr/local/bin/osg-display-start
fi
if [ "$#" -gt 0 ]; then
  exec "$@"
fi
exec sleep infinity
